This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./index.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file index.acn....done (19 entries accepted, 0 rejected).
Sorting entries....done (78 comparisons).
Generating output file index.acr....done (32 lines written, 0 warnings).
Output written in index.acr.
Transcript written in index.alg.
